config/routes.rb
Rails.application.routes.draw do
  resources :movies, :only => :index do # => tagアクションを追加しました。
    collection do
      get 'tag'
      get 'favourite'
      get 'find'
      get 'sort'
    end
  end
  resources :tags,       :only => :index
  resources :girls,      :only => :index

  root  'movies#index'

end

app/models/girl.rb
class Girl < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  acts_as_taggable_on :tags, :girls
end

app/models/translate_tag.rb
class TranslateTag < ActiveRecord::Base
end

app/models/translate_title.rb
class TranslateTitle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/girls_controller.rb
class GirlsController < ApplicationController
	def index
		@girls = Girl.paginate(page: params[:page], per_page: 40)
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	before_action :sort_method, :list_method, :current_url

	def index
		@movies = Movie.order(@sort).paginate(page: params[:page])
	    respond_to do |format|
	      format.html 
	      format.js { render 'sort.js.erb' }
	    end
	end

	def tag
		@name = params[:name]
		@movies = Movie.tagged_with(params[:name]).order(@sort).paginate(page: params[:page])
	    respond_to do |format|
			format.html { render 'index' }
			format.js   { render 'sort.js.erb' }
	    end

	end

	def favourite
		cookies[:user_name] = '4'
		content = cookies[:local_favourite]

		if content
			cookieArray = content.split('/')
		end

		@movies = Movie.where(id: cookieArray ).order(@sort).paginate(page: params[:page])

	    respond_to do |format|
			format.html { render 'index' }
			format.js   { render 'sort.js.erb' }
	    end
	end

	def find
		@movies = Movie.search(title_cont: params[:search_string])
		@movies = @movies.result.order(@sort).paginate(page: params[:page])
	    respond_to do |format|
			format.html { render 'index' }
			format.js   { render 'sort.js.erb' }
	    end
	end

	private
		def current_url
			@current = request.url
		end
		def list_method
			if params[:listtype].blank?
				if session[:listtype].blank?
					@listtype = 'og-grid'
				else
					@listtype = session[:listtype]
				end
			else
				session[:listtype] = params[:listtype]
				@listtype = params[:listtype]
			end
		end
		def sort_method

			if params[:sort].blank?
				sort_id = session[:sort]
			else
				session[:sort] = params[:sort]
				sort_id = params[:sort]
			end

			@selected = sort_id
			if sort_id.nil?
				sort = 'id'
				direction = 'asc'
				selected = 1
			else
				sort_num = sort_id.to_i
				if sort_num >= 10
					sort_num -= 10;
					direction = 'desc'
				else
					direction = 'asc'
				end
				case sort_num
					when 1 then
						sort = 'created_at'
					when 2 then
						sort = 'plays'
					when 3 then
						sort = 'title'
				end
			end
			@sort = "#{sort} #{direction}"
		end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Movie.tag_counts_on(:tags)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/girls/index.html.erb
		<article>
			<div id ="main" class="container">

				<div id="contents">
				<%= will_paginate %>
					<ul id="og-grid_gils" class="og-grid_gils">
						<% @girls.each do |girl| %>
							<li>
								<div class="chapter_girls">
									<img class ="previewEvent" src=<%= "/assets/girls/#{girl.name_alpha}.jpg" %> alt="img01"/>
									<p class ="previewEvent"><%= "#{girl.name}(#{girl.name_hira})" %></p>
									<table>
										<tr>
											<th>生年月日</th>
											<td><%= girl.birthday %></td>
										</tr>
										<tr>
											<th>身長</th>
											<td><%= girl.tall %></td>
										</tr>
										<tr>
											<th>サイズ</th>
											<td><%= "B#{girl.bust} W#{girl.west} H#{girl.hip}"%></td>
										</tr>
										<tr class="row-last">
											<th>出身地</th>
											<td><%= girl.hometown %></td>
										</tr>
									</table>
								</div>
							</li>
						<% end %>
					</ul>
				<%= will_paginate %>
				</div>
			</div>
		</article>


app/views/layouts/_footer.html.erb
		<footer>
			<div id="footer-bottom" class="container">
				<div class="footer-top clearfix">
					<div class="one-third clearfix">
						<h2>Sitemap</h2>
						<p><a>Home</a></p>
						<p><a>Girls</a></p>
						<p><a>Tags</a></p>
						<p><a>Favourite</a></p>
					</div>
					<div class="one-third">
					</div>
					<div class="one-third last">
					</div>
				</div>
			</div>
		</footer>

app/views/layouts/_header.html.erb

		<header>
			<div class="container">


				<div id="menu-main">

						<ul class="menu">

							<li class="toplogo" onclick="window.location = '/';" style="cursor:pointer;">
								<i class="glyphicon glyphicon-home"></i>
							</li>
							<li id="fat-menu" class="dropdown">
								<%= link_to "Girls", girls_path %>
								<ul>
									<li><a href="#">A</a></li>
									<li><a href="#">B</a></li>
									<li><a href="#">C</a></li>
								</ul>
							</li>
							<li class="menu-item">
								<%= link_to "Tags", tags_path %>
							</li>
							<li class="menu-item">
								<%= link_to "Favourites", favourite_movies_path %>
							</li>

							<li id="submenu">

								<div id="topSearch">

									<div class="search">
										<%= form_tag("/movies/find", :method => :get) do %>
										<%= text_field_tag :search_string %>
										<%= image_submit_tag("search_button.png") %>
										<% end %>
									</div><!-- search -->
								</div>
							</li>




						</ul>
				</div>
			</div>
		</header><!-- header -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>

		<link rel="stylesheet" type="text/css" href="http://necolas.github.io/normalize.css/3.0.1/normalize.css">
		<!-- Google Font -->
		<style type="text/css">
		  @import url("http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800");
		</style>

    <%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>

	<% flash.each do |key, value| %>
	  <div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<%= yield %>
	<%= yield :javascript_includes %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/movies/_result.html.erb
					<ul id="og-grid" class=<%=listtype%>>
						<% movies.each do |movie| %>
							<li>
								<a data-id=<%= movie.id %> data-hlink=<%= movie.url %> data-largesrc=<%= movie.embed %> data-title=<%= movie.title %> data-description=<%= movie.title %>>
									<div class="chapter">
										<img class ="previewEvent" src=<%= "/assets/movies/#{movie.image_path}" %> alt="img01"/>
										<div class="og-right">
											<p><%= movie.title %></p>
											<table>
												<tr>
													<th>女優</th>
													<td class="time"></td>
												</tr>
												<tr>
													<th>タグ</th>
													<td class="tag">
														<% tag_cloud(movie.tag_counts_on(:tags), %w(dummy1 dummy2 dummy3 dummy4)) do |tag, css_class| %>
														  <%= link_to tag.name, { :action => :tag, :name => tag.name }, :class => css_class %>
														<% end %>
													</td>
												</tr>
											</table>
										</div>
									</div>
								</a>
							</li>
						<% end %>
					</ul>

app/views/movies/index.html.erb

		<article>
<div id="soba-widget-publisher-SCbwhTftOWarGqYA" data-width="320" data-height="240"></div> 
<script src="http://widgets.soba-project.com/apps/QEUGteCpolvbvgAG/videos/SCbwhTftOWarGqYA/publisher.js" type="text/javascript"></script> 
			<div id ="main" class="container">

<%#
				<div id="filter">
	                <ul class="dopt-accordion light-theme arrow-tri">
		                <li><input class="title-option" id="accx1" name="accordion-2" type="checkbox"><label class="title-panel" for="accx1" onclick="">
		                        <span>
		                            <i class="icon-tasks"></i>Settings</span></label>
		                    <div class="accordion-content">
		                        <div class="wrap-content">
									<h3>Filter</h3>
									<div id="filtermenu" class="row">
										<ul>
											<li class="filter-site">
												<img class="share-site" src="/assets/logo_xvideos.png" alt="xvideos">
												<div class="switch-container">
													<label class="switch">
														<input type="checkbox" class="switch-input" checked>
														<span class="switch-label" data-on="On" data-off="Off"></span>
														<span class="switch-handle"></span>
													</label>
												</div>
											</li>
										</ul>
									</div>
		                        </div>
		                    </div>
		                </li>
	            	</ul>
				</div>
%>
				<div id="contents">
					<%= will_paginate %>

					<div id="view-toggle-wrapper">
						<ul id="menu-viewer-toggle"">
							<li class="moviebox-counter">
								<a><%= @movies.count %> movies</a>
							</li>
							<label for="category" class="select-wrap entypo-down-open-mini">
									<% choices = [['投稿日時が新しい順', 11],['投稿日時が古い順', 1],['再生回数が多い順', 12], ['再生回数が少ない順', 2], ['タイトル(昇順)', 3], ['タイトル(降順)', 13]] %>
									<%= select "movie", "sort", choices, selected: @selected %>
							</label>

							<li class="moviebox-list">
								<i class ="glyphicon glyphicon-th-list" style="color: white;">></i>
								<% if @current.index("?") then %>
									<% listurl = @current + '&listtype=og-list' %>
								<% else %>
									<% listurl = @current + '?listtype=og-list' %>
								<% end %>
								<%= link_to 'LIST', listurl, remote:true, class:"ajax-list" %>
							</li>

							<li class="moviebox-grid">
								<i class ="glyphicon glyphicon-th" style="color: white;">></i>
								<% if @current.index("?") then %>
									<% gridurl = @current + '&listtype=og-grid' %>
								<% else %>
									<% gridurl = @current + '?listtype=og-grid' %>
								<% end %>
								<%= link_to 'GRID', gridurl, remote:true, class:"ajax-grid" %>

							</li>
						</ul>
					</div>

					<div id="ajax_result">
						<%= render :partial => 'result', :locals => { :movies => @movies, :listtype => @listtype } %>
					</div>
					<%= will_paginate %>
				</div>

			</div>
		</article>
	<% content_for :javascript_includes do %>
	  <%= javascript_include_tag "grid.js" %>
	<% end %>

	<script>
	$(function(){

		$('.ajax-list').on('ajax:success', function(event, data, status) {
			Grid.init();
		});

		$('.ajax-grid').on('ajax:success', function(event, data, status) {
			Grid.init();
		});

		$('#movie_sort').change(function() {

			var sortMethod = $(this).val(),
				currentUrl = location.href;
			$.ajax({
				url: currentUrl,
				type: "GET",
				data: {
					sort: sortMethod
				},
				dataType: "script",
				success: function(data){
					Grid.init();
				}
			});
		});

	});
	</script>

	<script data-turbolinks-eval="false">
		$(document).on('page:change', function(e) {
			Grid.init();
		});
	</script>

app/views/movies/sort.js.erb
$('#ajax_result').html("<%= escape_javascript(render :partial => 'result', :locals => { :movies => @movies, :listtype => @listtype } ) %>");

app/views/tags/index.html.erb
		<article>
			<div id ="main" class="container">
				<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
				  <%= link_to tag.name, { :controller=>"movies", :action => :tag, :name => tag.name }, :class => css_class %>
				<% end %>
			</div>
		</article>